Display dashboard annotations
VolkovLabs/volkovlabs-calendar-panel pull request #194
Opened 2024-05-30 14:47 UTC by vitPinchuk

Resolves: #186

2024-06-03 05:26 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-06-04 12:17 UTC, mikhail-vl commented on src/hooks/useAnnotationEvents.ts
> +            text: annotationObject.title[index],
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading '0')
    at eval (useAnnotationEvents.ts:73:41)
    at Array.map (<anonymous>)
    at eval (useAnnotationEvents.ts:71:53)
    at Array.flatMap (<anonymous>)
    at eval (useAnnotationEvents.ts:59:48)
    at gd (react-dom.production.min.js:244:332)
    at qd (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at R (scheduler.production.min.js:13:203)
    at MessagePort.de (scheduler.production.min.js:14:128)
```

2024-06-04 12:18 UTC, mikhail-vl commented on src/hooks/useAnnotationEvents.ts
> +            text: annotationObject.title[index],
1. Add annotation query.
2. It should be displayed on the panel.
3. Click on Dashboard Refresh button.
4. Error displayed.

2024-06-04 12:19 UTC, mikhail-vl requested changes
Please update and resubmit.

2024-06-05 09:49 UTC, vitPinchuk commented on src/hooks/useAnnotationEvents.ts
> +            text: annotationObject.title[index],
updated

2024-06-06 11:25 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-06-07 04:57 UTC, mikhail-vl commented
@vitPinchuk Please add `text` as description in addition to title.

![Uploading Screenshot 2024-06-07 at 12.57.28 AM.png…]()

2024-06-07 04:59 UTC, mikhail-vl requested changes
Please add text to display additional information.

2024-06-10 04:01 UTC, mikhail-vl approved these changes
Looks good!

2024-06-10 04:02 UTC, merged